# Generated by Django 6.0.5 on 2026-06-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('asistencias_totales', models.IntegerField(default=0)),
                ('clases_totales', models.IntegerField(default=30)),
                ('promedio_actual', models.FloatField(default=0.0)),
            ],
        ),
    ]
