# Generated by Django 6.0.5 on 2026-06-03 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.IntegerField()),
                ('seccion', models.CharField(max_length=1)),
                ('turno', models.CharField(default='Matutino', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='alumnos.grupo'),
        ),
    ]
