# Generated by Django 6.0.5 on 2026-07-09 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_remove_grupo_turno_alumno_total_tareas_encargadas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='maestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='seccion',
            field=models.CharField(max_length=10),
        ),
    ]
