# Generated by Django 6.0.5 on 2026-08-06 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_grupo_maestro_alter_grupo_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaEncargada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_encargo', models.DateField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_encargadas', to='alumnos.grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_encargadas', to='alumnos.materia')),
            ],
        ),
    ]
