# Generated by Django 6.0.5 on 2026-08-09 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_tareaencargada'),
    ]

    operations = [
        migrations.CreateModel(
            name='InasistenciaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_faltas', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to='alumnos.alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias_periodo', to='alumnos.grupo')),
            ],
            options={
                'verbose_name': 'Inasistencia por Periodo',
                'verbose_name_plural': 'Inasistencias por Periodo',
            },
        ),
    ]
