# Generated by Django 6.0.5 on 2026-08-12 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_inasistenciaperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inasistenciaperiodo',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to='alumnos.materia'),
        ),
    ]
