# Generated by Django 6.0.5 on 2026-08-12 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_inasistenciaperiodo_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTareasPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodo', models.CharField(help_text="Ej. 'Semana 1 al 15 Sep' o 'Bloque 1'", max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_tareas_encargadas', models.PositiveIntegerField(default=0, help_text='Total de tareas encargadas a todo el grupo en este periodo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_periodos', to='alumnos.grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_periodos', to='alumnos.materia')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTareaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tareas_no_entregadas', models.PositiveIntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_tareas_periodo', to='alumnos.alumno')),
                ('registro_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_alumnos', to='alumnos.registrotareasperiodo')),
            ],
            options={
                'unique_together': {('registro_periodo', 'alumno')},
            },
        ),
    ]
