# Generated by Django 6.0.5 on 2026-08-13 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_registrotareasperiodo_detalletareaalumno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalletareaalumno',
            options={'verbose_name': 'Detalle de Tarea por Alumno', 'verbose_name_plural': 'Detalles de Tareas por Alumno'},
        ),
        migrations.AlterModelOptions(
            name='registrotareasperiodo',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Registro de Tareas por Periodo', 'verbose_name_plural': 'Registros de Tareas por Periodo'},
        ),
        migrations.AlterField(
            model_name='registrotareasperiodo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tareas', to='alumnos.grupo'),
        ),
        migrations.AlterField(
            model_name='registrotareasperiodo',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tareas', to='alumnos.materia'),
        ),
        migrations.AlterField(
            model_name='registrotareasperiodo',
            name='nombre_periodo',
            field=models.CharField(blank=True, help_text='Se genera automáticamente según las fechas', max_length=150),
        ),
        migrations.AlterField(
            model_name='registrotareasperiodo',
            name='total_tareas_encargadas',
            field=models.PositiveIntegerField(default=0, help_text='Total de tareas encargadas en este periodo'),
        ),
        migrations.CreateModel(
            name='RegistroInasistenciasPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodo', models.CharField(blank=True, help_text='Se genera automáticamente según las fechas', max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_inasistencias', to='alumnos.grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_inasistencias', to='alumnos.materia')),
            ],
            options={
                'verbose_name': 'Registro de Inasistencias por Periodo',
                'verbose_name_plural': 'Registros de Inasistencias por Periodo',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleInasistenciaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_faltas', models.PositiveIntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_inasistencias_periodo', to='alumnos.alumno')),
                ('registro_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_alumnos', to='alumnos.registroinasistenciasperiodo')),
            ],
            options={
                'verbose_name': 'Detalle de Inasistencia por Alumno',
                'verbose_name_plural': 'Detalles de Inasistencias por Alumno',
                'unique_together': {('registro_periodo', 'alumno')},
            },
        ),
    ]
